### ISSUE TITLE
Permission Error on Intro_to_DP02

### ISSUE THREAD

**Issue by aepreston439** [rubin-dp0/tutorial-notebooks#181]
Hello,

I have opted for following the guide that was posted as a link (https://dp0-2.lsst.io/tutorials-examples/cmdline-beginner.html) rather than doing the follow along version in JL/JN. I have been following along with the guide and everything has been working until I got to step 5.3 in the follow along that is also technically step 2.5 in the JN/JL version. Specifically, the line: 

plt.savefig('color-magnitude.pdf')

does not work for me. When I attempt this line I get returned:

PermissionError: [Errno 13] Permission denied: 'color-magnitude.pdf'

Originally, I thought this might be some sort of naming convention error so I did attempt to name the file without a special character but I still end up with the same error code. I did verify that all of my code up to this point was correctly input and working. This step does not exist in the JL/JN version. The step that takes its place in the secondary version is:

plt.show()

which does work. Please advise.

**Comment by MelissaGraham** [comment]
Hi @aepreston439, thanks for using the command line tutorial and for reporting this issue.

My first suspicion is that perhaps you're running through this in a read-only directory. In the RSP, for all users the /notebooks/tutorial-notebooks/ directory is read only, for example.

But the home directory should be writeable. Try a fix of 

`plt.savefig('~/color-magnitude.pdf')` 

If that works, we'll update our tutorial. If not, let us know and we'll continue to troubleshoot on this.

**Comment by aepreston439** [comment]
Hi @MelissaGraham, thank you so much for the speedy reply. This was the return of trying to save the info with that naming convention:

>>> plt.savefig('~/color-magnitude.pdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/pyplot.py", line 1119, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backends/backend_pdf.py", line 2800, in print_pdf
    file = PdfFile(filename, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backends/backend_pdf.py", line 688, in __init__
    fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/cbook.py", line 483, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/color-magnitude.pdf'
>>>

**Comment by MelissaGraham** [comment]
Hello, it looks like the command was missing the tilde, the `~`.

But an alternative is to use the full path to your home directory, so try the following instead, but replace YOURUSERNAME with your actual user name, so that `savefig` is being passed the full path to your home directory.

`plt.savefig('/home/YOURUSERNAME/color-magnitude.pdf')`

**Comment by aepreston439** [comment]
Hi again,

Deepest apologies, I'm not sure if I posted the incorrect lines or what happened there. Here should be the correct code after I attempted it again with the ~ addition

>>> plt.savefig('~/color-magnitude.pdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/pyplot.py", line 1119, in savefig
    res = fig.savefig(*args, **kwargs)  # type: ignore[func-returns-value]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/figure.py", line 3390, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    result = print_method(
             ^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2043, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backends/backend_pdf.py", line 2800, in print_pdf
    file = PdfFile(filename, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/backends/backend_pdf.py", line 688, in __init__
    fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lsst/software/stack/conda/miniconda3-py38_4.9.2/envs/lsst-scipipe-8.0.0/lib/python3.11/site-packages/matplotlib/cbook.py", line 483, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/color-magnitude.pdf'
>>>

**Comment by aepreston439** [comment]
Okay I am realizing now that for some reason, despite copy/pasting from the notebook and verifying that the ~ was in the line of code, for some reason when I post here it removes the ~ but I can assure you it is there. However, for reference, I have attached a screenshot of the same code:

![Screenshot (7)](https://github.com/rubin-dp0/tutorial-notebooks/assets/159815789/da4d9e85-0e36-4e59-900a-08d812fb3d10)

**Comment by MelissaGraham** [comment]
Oh I see it, odd copy-paste malfunction. But, I found the same issue with `plt.savefig('~/color-magnitude.pdf')`. Instead of trying to figure out why that didn't work, use the full path. I've verified that this worked for me.

`plt.savefig('/home/USERNAME/color-magnitude.pdf')`

Also, the tutorial's version of just `plt.savefig('color-magnitude.pdf')` worked for me when I was running the tutorial in my home directory. So you could try exiting python, navigating to your home directory in the terminal, and then rerunning it. From the screenshot above I do infer that you're running the tutorial in the read-only directory of `notebooks/tutorial-notebooks/`. So that's probably the issue.

**Comment by aepreston439** [comment]
Thank you very much for your help, I appreciate it greatly! Have a wonderful rest of your day!
